name: 京东脚本定时运行

on:
  schedule:
    - cron: '0 12,23 * * *'  # 每天 12:00 和 23:00 运行

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安装依赖
        run: npm install

      - name: 设置环境变量
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
        run: |
          echo "JD_COOKIE=$JD_COOKIE" >> $GITHUB_ENV

      - name: 运行脚本
        run: node jd_scripts.js  # 这里假设运行 jd_scripts.js，根据实际脚本修改
